
# ============================================================================
# Name        : 23_find_the_difference.py
# Author      : Saranya Balakrishnan
# Mail Id     : saranyab0925@gmail.com
# ============================================================================

"""
Given two strings s and t which consist of only lowercase letters.

String t is generated by random shuffling string s and then add one more letter at a random position.

Find the letter that was added in t.

Example:

Input:
s = "abcd"
t = "abcde"

Output:
e

Explanation:
'e' is the letter that was added.
"""
class Solution(object):
    def findTheDifference(self, s, t):
        """
        :type s: str
        :type t: str
        :rtype: str
        
        s_dict ={}
        if len(s)> len(t):
            for i in s:
                if i in s_dict:
                    s_dict[i] += 1
                else:
                    s_dict[i] = 1
            print(s_dict)

            for j in t:
                if j not in s_dict:
                    return j
                elif s_dict[j] == 0:
                    return j
                else:
                    s_dict[j] -= 1
                    return j
        elif len(t)>len(s):
             for i in t:
                 if i in s_dict:
                     s_dict[i] += 1
                 else:
                     s_dict[i] = 1

             for j in s:
                 if j not in s_dict:
                     return j
                 elif s_dict[j] == 0:
                     return j
                 else:
                     s_dict[j] -= 1
                     return s_dict[j]*j
"""
        s = sorted(s)
        t = sorted(t)
        # convert t to ascii code
        sum_up = 0
        for i in t:
            # add all the ascii value of t
            sum_up += ord(i)
        for j in s:
            # remove all the ascii value of s
            sum_up -= ord(j)
        # convert the left over ascii value back to chr   
        return chr(sum_up) 

if __name__ == "__main__":
    test = Solution()
    s = "a"
    t = "aaa"
    res = test.findTheDifference(s,t)
    print(res)
